package com.hongwei.model.nba

enum class NbaTeams(val short: String) {
    ATL("atl"),
    BKN("bkn"),
    BOS("bos"),
    CHA("cha"),
    CHI("chi"),
    CLE("cle"),
    DAL("dal"),
    DEN("den"),
    DET("det"),
    GS("gs"),
    HOU("hou"),
    IND("ind"),
    LAC("lac"),
    LAL("lal"),
    MEM("mem"),
    MIA("mia"),
    MIL("mil"),
    MIN("min"),
    NO("no"),
    NY("ny"),
    OKC("okc"),
    ORL("orl"),
    PHI("phi"),
    PHX("phx"),
    POR("por"),
    SAC("sac"),
    SA("sa"),
    TOR("tor"),
    UTAH("utah"),
    WSH("wsh")
}